spring:
 datasource:
  url: jdbc:sqlserver://elecdeviceserver.database.windows.net:1433;database=ElecDB;user=elecdeviceserver@elecdeviceserver;password={Sksaini@0798};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: elecdeviceserver
  password: Sksaini@0798
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   
server:
 port: 8081